name: Build and Deploy Streamlit App with Docker

# Trigger the action when code is pushed to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Define the job to build and run the Docker image
  build:
    runs-on: ubuntu-latest  # Use Ubuntu environment for the job

    steps:
    # Step 1: Checkout the repository to the GitHub runner
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker (GitHub Action for Docker Build and Push)
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    # Step 3: Build the Docker image using the Dockerfile
    - name: Build Docker image
      run: |
        docker build -t streamlit-app .

    # Step 4: Run the Streamlit app in a container
    - name: Run Streamlit app
      run: |
        docker run -d -p 8501:8501 streamlit-app
